"""initial_schema

Revision ID: cf3d8aef1f11
Revises: 
Create Date: 2026-05-25 16:04:22.516029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf3d8aef1f11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('milestone_category', sa.String(length=30), nullable=True, comment='qualification_exam | level_exam | spring_exam | autumn_exam | mock_exam | school_exam | registration | volunteer_fill | result_release | comprehensive_eval | custom'),
    sa.Column('timing', sa.String(length=15), nullable=True, comment='15d_before | 3d_before'),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of action item objects'),
    sa.Column('footer_tip', sa.String(length=500), nullable=True),
    sa.Column('applicable_grades', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applicable_subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quote_category', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True, comment='daily_encouragement | study_method | pre_exam_motivation | stress_relief | post_exam_relief | parent_child_warmth | famous_quotes | gao1_special'),
    sa.Column('applicable_grades', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applicable_phase', sa.String(length=20), nullable=True, comment='normal | pre_exam_30d | pre_exam_7d | post_exam | all'),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.String(length=20), nullable=False, comment="e.g. 'chinese', 'math'"),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=True, comment='required | elective'),
    sa.Column('gaokao_max_score', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('openid', sa.String(length=128), nullable=False, comment='WeChat openid'),
    sa.Column('union_id', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False, comment='1, 2, or 3'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_nodes_parent', 'knowledge_nodes', ['parent_id'], unique=False)
    op.create_index('ix_knowledge_nodes_subject_level', 'knowledge_nodes', ['subject_id', 'level'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=True, comment='gao1 | gao2 | gao3'),
    sa.Column('district', sa.String(length=20), nullable=True),
    sa.Column('has_selected_subjects', sa.Boolean(), nullable=False),
    sa.Column('selected_subject_1', sa.String(length=20), nullable=True),
    sa.Column('selected_subject_2', sa.String(length=20), nullable=True),
    sa.Column('selected_subject_3', sa.String(length=20), nullable=True),
    sa.Column('has_jan_english_exam', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_quote_favorites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['daily_quotes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quote_id', name='uq_user_quote_favorite')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.String(length=10), nullable=True, comment='free | standard | premium'),
    sa.Column('billing_type', sa.String(length=25), nullable=True, comment='monthly | yearly | lifetime_high_school'),
    sa.Column('price_paid', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('trial_expires_at', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_subscriptions_user_plan', 'user_subscriptions', ['user_id', 'plan'], unique=False)
    op.create_table('error_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.String(length=20), nullable=False),
    sa.Column('knowledge_node_id', sa.Uuid(), nullable=True),
    sa.Column('error_type', sa.String(length=20), nullable=True, comment='careless | concept_unclear | method_unknown | other'),
    sa.Column('source', sa.String(length=20), nullable=True, comment='monthly | weekly | homework | mock | other'),
    sa.Column('question_image_url', sa.String(length=512), nullable=False),
    sa.Column('correction_image_url', sa.String(length=512), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_error_notes_student_created', 'error_notes', ['student_id', 'created_at'], unique=False, postgresql_using='btree')
    op.create_index('ix_error_notes_student_knowledge', 'error_notes', ['student_id', 'knowledge_node_id'], unique=False)
    op.create_index('ix_error_notes_student_subject', 'error_notes', ['student_id', 'subject_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('exam_type', sa.String(length=20), nullable=True, comment='monthly | midterm | final | mock1 | mock2 | mock3 | other'),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exams_student_date', 'exams', ['student_id', 'exam_date'], unique=False)
    op.create_table('growth_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=True, comment='award | progress | performance | breakthrough | memo'),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True, comment='academic_competition | sports | comprehensive | social_practice | other'),
    sa.Column('awarding_body', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('linked_quote_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_quote_id'], ['daily_quotes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_growth_records_student_date', 'growth_records', ['student_id', 'record_date'], unique=False, postgresql_using='btree')
    op.create_index('ix_growth_records_student_type', 'growth_records', ['student_id', 'record_type'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=True, comment='system | custom'),
    sa.Column('student_id', sa.Uuid(), nullable=True, comment='NULL for system milestones'),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_end_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True, comment='qualification_exam | level_exam | spring_exam | autumn_exam | mock_exam | school_exam | registration | volunteer_fill | result_release | comprehensive_eval | custom'),
    sa.Column('applicable_grades', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='e.g. ["gao3"]'),
    sa.Column('applicable_subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applicable_districts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requires_jan_english', sa.Boolean(), nullable=False),
    sa.Column('remind_15d', sa.Boolean(), nullable=False),
    sa.Column('remind_3d', sa.Boolean(), nullable=False),
    sa.Column('action_card_15d_id', sa.Uuid(), nullable=True),
    sa.Column('action_card_3d_id', sa.Uuid(), nullable=True),
    sa.Column('is_dynamic_date', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_card_15d_id'], ['action_cards.id'], ),
    sa.ForeignKeyConstraint(['action_card_3d_id'], ['action_cards.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_milestones_category', 'milestones', ['category'], unique=False)
    op.create_index('ix_milestones_event_date', 'milestones', ['event_date'], unique=False)
    op.create_index('ix_milestones_student', 'milestones', ['student_id'], unique=False)
    op.create_table('school_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('knowledge_node_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_quote_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('display_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['daily_quotes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'display_date', name='uq_user_quote_history_student_date')
    )
    op.create_index('ix_user_quote_history_student_date', 'user_quote_history', ['student_id', 'display_date'], unique=False)
    op.create_table('exam_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('score_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='score / max_score * 100'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'subject_id', name='uq_exam_score_exam_subject')
    )
    op.create_index('ix_exam_scores_exam', 'exam_scores', ['exam_id'], unique=False)
    op.create_table('milestone_reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=False),
    sa.Column('timing', sa.String(length=15), nullable=True, comment='15d_before | 3d_before'),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('action_items_checked', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'milestone_id', 'timing', name='uq_milestone_reminder_student_milestone_timing')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milestone_reminders')
    op.drop_index('ix_exam_scores_exam', table_name='exam_scores')
    op.drop_table('exam_scores')
    op.drop_index('ix_user_quote_history_student_date', table_name='user_quote_history')
    op.drop_table('user_quote_history')
    op.drop_table('school_progress')
    op.drop_index('ix_milestones_student', table_name='milestones')
    op.drop_index('ix_milestones_event_date', table_name='milestones')
    op.drop_index('ix_milestones_category', table_name='milestones')
    op.drop_table('milestones')
    op.drop_index('ix_growth_records_student_type', table_name='growth_records')
    op.drop_index('ix_growth_records_student_date', table_name='growth_records', postgresql_using='btree')
    op.drop_table('growth_records')
    op.drop_index('ix_exams_student_date', table_name='exams')
    op.drop_table('exams')
    op.drop_index('ix_error_notes_student_subject', table_name='error_notes')
    op.drop_index('ix_error_notes_student_knowledge', table_name='error_notes')
    op.drop_index('ix_error_notes_student_created', table_name='error_notes', postgresql_using='btree')
    op.drop_table('error_notes')
    op.drop_index('ix_user_subscriptions_user_plan', table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_table('user_quote_favorites')
    op.drop_table('students')
    op.drop_index('ix_knowledge_nodes_subject_level', table_name='knowledge_nodes')
    op.drop_index('ix_knowledge_nodes_parent', table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('daily_quotes')
    op.drop_table('action_cards')
    # ### end Alembic commands ###
